name: Teste PC Windows

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Informações de conexão
        shell: powershell
        run: |
          Write-Host "===== PC WINDOWS ====="

          Write-Host ""
          Write-Host "Nome da máquina:"
          hostname

          Write-Host ""
          Write-Host "Endereços IPv4:"
          Get-NetIPAddress -AddressFamily IPv4 |
            Where-Object {$_.IPAddress -notlike "127.*"} |
            Select-Object InterfaceAlias, IPAddress

          Write-Host ""
          Write-Host "RDP:"
          Get-Service TermService |
            Select-Object Name, Status

          Write-Host ""
          Write-Host "Porta RDP:"
          Get-NetTCPConnection -LocalPort 3389 -ErrorAction SilentlyContinue |
            Select-Object LocalAddress, LocalPort, State

          Write-Host ""
          Write-Host "===== FIM DO TESTE ====="
